### ISSUE TITLE
Arrumar produto_id

### ISSUE THREAD

**Issue by FrancineMoraes** [ViniciusVonAhn/MercadoWeb#3]
Trocar o nome do id na tabela produto de "produto_id" para "id"

**Comment by ViniciusVonAhn** [comment]
Ta bom assim

**Comment by FrancineMoraes** [comment]
não tá bom nada

![captura de tela de 2018-06-03 16-21-08](https://user-images.githubusercontent.com/28935143/40890352-17a3fca6-674b-11e8-9cfc-da6435917f42.png)
![captura de tela de 2018-06-03 16-21-23](https://user-images.githubusercontent.com/28935143/40890353-17f51a50-674b-11e8-8dfb-d1a4caa76500.png)
![captura de tela de 2018-06-03 16-21-39](https://user-images.githubusercontent.com/28935143/40890354-181b7fa6-674b-11e8-95ca-48f5d191dcfb.png)
