### ISSUE TITLE
Arrumar método update

### ISSUE THREAD

**Issue by FrancineMoraes** [ViniciusVonAhn/MercadoWeb#4]
Fazer ajustes no método update. 
Método update não está editando. Quando eu vou editar um produto em vez de ele editar as informações daquele determinado produto, ele está pegando as informações que estou alterando e criando um novo produto com elas.

![captura de tela de 2018-05-31 15-43-51](https://user-images.githubusercontent.com/28935143/40801506-79449a24-64e9-11e8-8c69-63020a2d36cf.png)

![captura de tela de 2018-05-31 15-43-54](https://user-images.githubusercontent.com/28935143/40801509-79970282-64e9-11e8-8a81-dfa0c655aad7.png)

**Comment by ViniciusVonAhn** [comment]
![lista dos produtos](https://user-images.githubusercontent.com/28817597/40879188-b5e0e368-6672-11e8-91c0-2b2463a5049b.png)

![alterando produto 1](https://user-images.githubusercontent.com/28817597/40879189-bce5cfca-6672-11e8-9807-fd6306dcf2d1.png)

![alterado](https://user-images.githubusercontent.com/28817597/40879191-c1d277ea-6672-11e8-84a0-f33185702321.png)

**Comment by ViniciusVonAhn** [comment]
fiz uma mudando no método, tenta e me avisa se deu certo.

**Comment by ViniciusVonAhn** [comment]
Erro estava no front edit.vue, mas já foi arrumado énois
